"""create application schema

Revision ID: 373c9d3f1e26
Revises: 
Create Date: 2026-08-10 16:19:41.749456
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '373c9d3f1e26'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE SCHEMA IF NOT EXISTS app")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('principal_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('ip_hash', sa.LargeBinary(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('success', 'failure', 'denied')", name='ck_security_audit_events_outcome'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_security_audit_events_principal_id'), 'security_audit_events', ['principal_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_security_audit_events_request_id'), 'security_audit_events', ['request_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_security_audit_events_tenant_id'), 'security_audit_events', ['tenant_id'], unique=False, schema='app')
    op.create_index('ix_security_audit_events_occurred', 'security_audit_events', ['occurred_at'], unique=False, schema='app')
    op.create_index('ix_security_audit_events_principal_occurred', 'security_audit_events', ['principal_id', 'occurred_at'], unique=False, schema='app', postgresql_where=sa.text('principal_id IS NOT NULL'))
    op.create_index('ix_security_audit_events_tenant_occurred', 'security_audit_events', ['tenant_id', 'occurred_at'], unique=False, schema='app')
    op.create_index('ix_security_audit_events_type_occurred', 'security_audit_events', ['event_type', 'occurred_at'], unique=False, schema='app')
    op.create_table('tenants',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('personal', 'team')", name='ck_tenants_kind'),
    sa.CheckConstraint("status IN ('active', 'suspended', 'deleted')", name='ck_tenants_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('ix_tenants_active_status', 'tenants', ['status'], unique=False, schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('principals',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('user', 'service')", name='ck_principals_kind'),
    sa.CheckConstraint("status IN ('active', 'suspended', 'deleted')", name='ck_principals_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['app.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_principals_id_tenant'),
    schema='app'
    )
    op.create_index(op.f('ix_app_principals_tenant_id'), 'principals', ['tenant_id'], unique=False, schema='app')
    op.create_index('ix_principals_tenant_active', 'principals', ['tenant_id', 'status'], unique=False, schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('uploader_principal_id', sa.Uuid(), nullable=False),
    sa.Column('storage_provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.LargeBinary(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('upload_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('scan_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('scan_detail', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('image', 'file')", name='ck_attachments_kind'),
    sa.CheckConstraint("processing_status IN ('not_requested', 'queued', 'processed', 'failed')", name='ck_attachments_processing_status'),
    sa.CheckConstraint("scan_status IN ('pending', 'clean', 'infected', 'failed')", name='ck_attachments_scan_status'),
    sa.CheckConstraint("upload_status IN ('pending_upload', 'uploaded', 'scanning', 'available', 'rejected', 'deleted')", name='ck_attachments_upload_status'),
    sa.ForeignKeyConstraint(['uploader_principal_id', 'tenant_id'], ['app.principals.id', 'app.principals.tenant_id'], name='fk_attachments_uploader_principal_tenant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_attachments_id_tenant'),
    schema='app'
    )
    op.create_index(op.f('ix_app_attachments_tenant_id'), 'attachments', ['tenant_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_attachments_uploader_principal_id'), 'attachments', ['uploader_principal_id'], unique=False, schema='app')
    op.create_index('ix_attachments_scan_work', 'attachments', ['scan_status'], unique=False, schema='app', postgresql_where=sa.text("scan_status IN ('pending', 'failed')"))
    op.create_index('ix_attachments_upload_expiry', 'attachments', ['upload_status', 'expires_at'], unique=False, schema='app')
    op.create_index('ix_attachments_uploader_created', 'attachments', ['tenant_id', 'uploader_principal_id', 'created_at'], unique=False, schema='app')
    op.create_index('uq_attachments_object_location', 'attachments', ['storage_provider', 'bucket', 'object_key'], unique=True, schema='app')
    op.create_table('conversations',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('owner_principal_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('title_source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_message_sequence', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_after_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_principal_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'archived', 'deleted')", name='ck_conversations_status'),
    sa.CheckConstraint('latest_message_sequence >= 0', name='ck_conversations_latest_sequence'),
    sa.CheckConstraint('version > 0', name='ck_conversations_version'),
    sa.ForeignKeyConstraint(['deleted_by_principal_id'], ['app.principals.id'], ),
    sa.ForeignKeyConstraint(['owner_principal_id', 'tenant_id'], ['app.principals.id', 'app.principals.tenant_id'], name='fk_conversations_owner_principal_tenant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_conversations_id_tenant'),
    sa.UniqueConstraint('thread_id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_conversations_owner_principal_id'), 'conversations', ['owner_principal_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False, schema='app')
    op.create_index('ix_conversations_owner_history', 'conversations', ['tenant_id', 'owner_principal_id', 'last_message_at', 'id'], unique=False, schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_conversations_purge_after', 'conversations', ['purge_after_at'], unique=False, schema='app', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('ix_conversations_status_history', 'conversations', ['tenant_id', 'status', 'last_message_at'], unique=False, schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('data_deletion_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_principal_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purge_after_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('failure_detail', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("reason IN ('user_request', 'retention', 'admin')", name='ck_data_deletion_requests_reason'),
    sa.CheckConstraint("status IN ('scheduled', 'running', 'completed', 'failed', 'cancelled')", name='ck_data_deletion_requests_status'),
    sa.CheckConstraint("target_type IN ('conversation', 'user', 'attachment')", name='ck_data_deletion_requests_target_type'),
    sa.ForeignKeyConstraint(['requested_by_principal_id'], ['app.principals.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['app.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_data_deletion_requests_requested_by_principal_id'), 'data_deletion_requests', ['requested_by_principal_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_data_deletion_requests_target_id'), 'data_deletion_requests', ['target_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_data_deletion_requests_tenant_id'), 'data_deletion_requests', ['tenant_id'], unique=False, schema='app')
    op.create_index('ix_data_deletion_requests_completed', 'data_deletion_requests', ['completed_at'], unique=False, schema='app')
    op.create_index('ix_data_deletion_requests_due', 'data_deletion_requests', ['status', 'purge_after_at'], unique=False, schema='app')
    op.create_index('ix_data_deletion_requests_target', 'data_deletion_requests', ['tenant_id', 'target_type', 'target_id'], unique=False, schema='app')
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('email_normalized', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('security_invalid_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending_verification', 'active', 'disabled', 'deleted')", name='ck_users_status'),
    sa.CheckConstraint('email_normalized = lower(email_normalized)', name='ck_users_email_normalized'),
    sa.ForeignKeyConstraint(['principal_id', 'tenant_id'], ['app.principals.id', 'app.principals.tenant_id'], name='fk_users_principal_tenant'),
    sa.PrimaryKeyConstraint('principal_id'),
    sa.UniqueConstraint('principal_id', 'tenant_id', name='uq_users_principal_tenant'),
    schema='app'
    )
    op.create_index(op.f('ix_app_users_tenant_id'), 'users', ['tenant_id'], unique=False, schema='app')
    op.create_index('ix_users_active_status', 'users', ['status'], unique=False, schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_users_active_email_normalized', 'users', ['email_normalized'], unique=True, schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('agent_runs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('model_alias', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('provider_model', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interrupt_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'interrupted', 'completed', 'failed', 'cancelled')", name='ck_agent_runs_status'),
    sa.ForeignKeyConstraint(['conversation_id', 'tenant_id'], ['app.conversations.id', 'app.conversations.tenant_id'], name='fk_agent_runs_conversation_tenant'),
    sa.ForeignKeyConstraint(['principal_id', 'tenant_id'], ['app.principals.id', 'app.principals.tenant_id'], name='fk_agent_runs_principal_tenant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_agent_runs_id_tenant'),
    schema='app'
    )
    op.create_index('ix_agent_runs_conversation_created', 'agent_runs', ['conversation_id', 'created_at'], unique=False, schema='app')
    op.create_index('ix_agent_runs_tenant_status_created', 'agent_runs', ['tenant_id', 'status', 'created_at'], unique=False, schema='app')
    op.create_index('ix_agent_runs_terminal_completed', 'agent_runs', ['completed_at'], unique=False, schema='app', postgresql_where=sa.text("status IN ('completed', 'failed', 'cancelled')"))
    op.create_index(op.f('ix_app_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_agent_runs_principal_id'), 'agent_runs', ['principal_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_agent_runs_tenant_id'), 'agent_runs', ['tenant_id'], unique=False, schema='app')
    op.create_index('uq_agent_runs_active_conversation', 'agent_runs', ['conversation_id'], unique=True, schema='app', postgresql_where=sa.text("status IN ('queued', 'running', 'interrupted')"))
    op.create_table('auth_one_time_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_principal_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_ip_hash', sa.LargeBinary(), nullable=True),
    sa.Column('request_user_agent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.CheckConstraint("purpose IN ('email_verify', 'password_reset')", name='ck_auth_one_time_tokens_purpose'),
    sa.ForeignKeyConstraint(['user_principal_id'], ['app.users.principal_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='app'
    )
    op.create_index(op.f('ix_app_auth_one_time_tokens_user_principal_id'), 'auth_one_time_tokens', ['user_principal_id'], unique=False, schema='app')
    op.create_index('ix_auth_one_time_tokens_expiry', 'auth_one_time_tokens', ['expires_at'], unique=False, schema='app')
    op.create_index('ix_auth_one_time_tokens_user_purpose_created', 'auth_one_time_tokens', ['user_principal_id', 'purpose', 'created_at'], unique=False, schema='app')
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_principal_id', sa.Uuid(), nullable=False),
    sa.Column('token_family_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('ip_hash', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_principal_id', 'tenant_id'], ['app.users.principal_id', 'app.users.tenant_id'], name='fk_auth_sessions_user_tenant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_family_id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_auth_sessions_tenant_id'), 'auth_sessions', ['tenant_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_auth_sessions_user_principal_id'), 'auth_sessions', ['user_principal_id'], unique=False, schema='app')
    op.create_index('ix_auth_sessions_active_user_expiry', 'auth_sessions', ['user_principal_id', 'expires_at'], unique=False, schema='app', postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('ix_auth_sessions_expiry', 'auth_sessions', ['expires_at'], unique=False, schema='app')
    op.create_table('revoked_access_tokens',
    sa.Column('jti', sa.Uuid(), nullable=False),
    sa.Column('user_principal_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_principal_id'], ['app.users.principal_id'], ),
    sa.PrimaryKeyConstraint('jti'),
    schema='app'
    )
    op.create_index(op.f('ix_app_revoked_access_tokens_user_principal_id'), 'revoked_access_tokens', ['user_principal_id'], unique=False, schema='app')
    op.create_index('ix_revoked_access_tokens_expiry', 'revoked_access_tokens', ['expires_at'], unique=False, schema='app')
    op.create_table('service_principals',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_by_user_principal_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_principal_id'], ['app.users.principal_id'], ),
    sa.ForeignKeyConstraint(['principal_id', 'tenant_id'], ['app.principals.id', 'app.principals.tenant_id'], name='fk_service_principals_principal_tenant'),
    sa.PrimaryKeyConstraint('principal_id'),
    sa.UniqueConstraint('principal_id', 'tenant_id', name='uq_service_principals_principal_tenant'),
    schema='app'
    )
    op.create_index(op.f('ix_app_service_principals_created_by_user_principal_id'), 'service_principals', ['created_by_user_principal_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_service_principals_tenant_id'), 'service_principals', ['tenant_id'], unique=False, schema='app')
    op.create_table('tenant_memberships',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_principal_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name='ck_memberships_role'),
    sa.CheckConstraint("status IN ('active', 'invited', 'removed')", name='ck_memberships_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['app.tenants.id'], ),
    sa.ForeignKeyConstraint(['user_principal_id'], ['app.users.principal_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'user_principal_id'),
    schema='app'
    )
    op.create_index('ix_memberships_user_status', 'tenant_memberships', ['user_principal_id', 'status'], unique=False, schema='app')
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('service_principal_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('secret_hash', sa.LargeBinary(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_principal_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_principal_id'], ['app.users.principal_id'], ),
    sa.ForeignKeyConstraint(['service_principal_id', 'tenant_id'], ['app.service_principals.principal_id', 'app.service_principals.tenant_id'], name='fk_api_keys_service_principal_tenant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_hash'),
    schema='app'
    )
    op.create_index('ix_api_keys_active_service_expiry', 'api_keys', ['service_principal_id', 'expires_at'], unique=False, schema='app', postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('ix_api_keys_expiry', 'api_keys', ['expires_at'], unique=False, schema='app')
    op.create_index('ix_api_keys_prefix', 'api_keys', ['key_prefix'], unique=False, schema='app')
    op.create_index(op.f('ix_app_api_keys_created_by_user_principal_id'), 'api_keys', ['created_by_user_principal_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_api_keys_service_principal_id'), 'api_keys', ['service_principal_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False, schema='app')
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('http_method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('request_fingerprint', sa.LargeBinary(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'completed', 'failed')", name='ck_idempotency_keys_status'),
    sa.ForeignKeyConstraint(['agent_run_id', 'tenant_id'], ['app.agent_runs.id', 'app.agent_runs.tenant_id'], name='fk_idempotency_keys_agent_run_tenant'),
    sa.ForeignKeyConstraint(['conversation_id', 'tenant_id'], ['app.conversations.id', 'app.conversations.tenant_id'], name='fk_idempotency_keys_conversation_tenant'),
    sa.ForeignKeyConstraint(['principal_id', 'tenant_id'], ['app.principals.id', 'app.principals.tenant_id'], name='fk_idempotency_keys_principal_tenant'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_idempotency_keys_agent_run_id'), 'idempotency_keys', ['agent_run_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_idempotency_keys_conversation_id'), 'idempotency_keys', ['conversation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_idempotency_keys_principal_id'), 'idempotency_keys', ['principal_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_idempotency_keys_tenant_id'), 'idempotency_keys', ['tenant_id'], unique=False, schema='app')
    op.create_index('ix_idempotency_keys_conversation', 'idempotency_keys', ['conversation_id'], unique=False, schema='app', postgresql_where=sa.text('conversation_id IS NOT NULL'))
    op.create_index('ix_idempotency_keys_expiry', 'idempotency_keys', ['expires_at'], unique=False, schema='app')
    op.create_index('uq_idempotency_keys_request', 'idempotency_keys', ['principal_id', 'http_method', 'route', 'idempotency_key'], unique=True, schema='app')
    op.create_table('messages',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rendered_text', sa.Text(), nullable=True),
    sa.Column('content_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('model_alias', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("content_status IN ('complete', 'partial', 'failed', 'redacted')", name='ck_messages_content_status'),
    sa.CheckConstraint("jsonb_typeof(content) = 'array'", name='ck_messages_content_array'),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system', 'tool')", name='ck_messages_role'),
    sa.CheckConstraint('sequence > 0', name='ck_messages_sequence'),
    sa.ForeignKeyConstraint(['agent_run_id', 'tenant_id'], ['app.agent_runs.id', 'app.agent_runs.tenant_id'], name='fk_messages_agent_run_tenant'),
    sa.ForeignKeyConstraint(['conversation_id', 'tenant_id'], ['app.conversations.id', 'app.conversations.tenant_id'], name='fk_messages_conversation_tenant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_messages_conversation_sequence'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_messages_id_tenant'),
    schema='app'
    )
    op.create_index(op.f('ix_app_messages_agent_run_id'), 'messages', ['agent_run_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_messages_tenant_id'), 'messages', ['tenant_id'], unique=False, schema='app')
    op.create_index('ix_messages_agent_run', 'messages', ['agent_run_id'], unique=False, schema='app', postgresql_where=sa.text('agent_run_id IS NOT NULL'))
    op.create_index('ix_messages_conversation_history', 'messages', ['conversation_id', 'sequence'], unique=False, schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['app.refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['app.auth_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='app'
    )
    op.create_index(op.f('ix_app_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False, schema='app')
    op.create_index('ix_refresh_tokens_expiry', 'refresh_tokens', ['expires_at'], unique=False, schema='app')
    op.create_index('ix_refresh_tokens_session_issued', 'refresh_tokens', ['session_id', 'issued_at'], unique=False, schema='app')
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('provider_call_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('input_redacted', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'timed_out', 'cancelled')", name='ck_tool_calls_status'),
    sa.ForeignKeyConstraint(['agent_run_id', 'tenant_id'], ['app.agent_runs.id', 'app.agent_runs.tenant_id'], name='fk_tool_calls_agent_run_tenant'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_tool_calls_agent_run_id'), 'tool_calls', ['agent_run_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_tool_calls_tenant_id'), 'tool_calls', ['tenant_id'], unique=False, schema='app')
    op.create_index('ix_tool_calls_active', 'tool_calls', ['status', 'created_at'], unique=False, schema='app', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_index('ix_tool_calls_tenant_tool_created', 'tool_calls', ['tenant_id', 'tool_name', 'created_at'], unique=False, schema='app')
    op.create_index('uq_tool_calls_run_sequence', 'tool_calls', ['agent_run_id', 'sequence'], unique=True, schema='app')
    op.create_table('message_attachments',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('attachment_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id', 'tenant_id'], ['app.attachments.id', 'app.attachments.tenant_id'], name='fk_message_attachments_attachment_tenant'),
    sa.ForeignKeyConstraint(['message_id', 'tenant_id'], ['app.messages.id', 'app.messages.tenant_id'], name='fk_message_attachments_message_tenant'),
    sa.PrimaryKeyConstraint('message_id', 'attachment_id'),
    sa.UniqueConstraint('attachment_id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_message_attachments_tenant_id'), 'message_attachments', ['tenant_id'], unique=False, schema='app')
    op.create_index('uq_message_attachments_position', 'message_attachments', ['message_id', 'position'], unique=True, schema='app')
    op.create_table('message_citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_message_citations_position'),
    sa.ForeignKeyConstraint(['message_id', 'tenant_id'], ['app.messages.id', 'app.messages.tenant_id'], name='fk_message_citations_message_tenant'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_message_citations_message_id'), 'message_citations', ['message_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_message_citations_tenant_id'), 'message_citations', ['tenant_id'], unique=False, schema='app')
    op.create_index('uq_message_citations_position', 'message_citations', ['message_id', 'position'], unique=True, schema='app')
    op.create_table('travel_preferences',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_principal_id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('confirmed', 'revoked', 'expired')", name='ck_travel_preferences_status'),
    sa.ForeignKeyConstraint(['source_message_id', 'tenant_id'], ['app.messages.id', 'app.messages.tenant_id'], name='fk_travel_preferences_source_message_tenant'),
    sa.ForeignKeyConstraint(['user_principal_id', 'tenant_id'], ['app.users.principal_id', 'app.users.tenant_id'], name='fk_travel_preferences_user_tenant'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_travel_preferences_source_message_id'), 'travel_preferences', ['source_message_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_travel_preferences_tenant_id'), 'travel_preferences', ['tenant_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_travel_preferences_user_principal_id'), 'travel_preferences', ['user_principal_id'], unique=False, schema='app')
    op.create_index('ix_travel_preferences_expiry', 'travel_preferences', ['expires_at'], unique=False, schema='app', postgresql_where=sa.text("status = 'confirmed'"))
    op.create_index('ix_travel_preferences_user_status', 'travel_preferences', ['tenant_id', 'user_principal_id', 'status'], unique=False, schema='app')
    op.create_index('uq_travel_preferences_confirmed_category', 'travel_preferences', ['user_principal_id', 'category'], unique=True, schema='app', postgresql_where=sa.text("status = 'confirmed' AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_travel_preferences_confirmed_category', table_name='travel_preferences', schema='app', postgresql_where=sa.text("status = 'confirmed' AND deleted_at IS NULL"))
    op.drop_index('ix_travel_preferences_user_status', table_name='travel_preferences', schema='app')
    op.drop_index('ix_travel_preferences_expiry', table_name='travel_preferences', schema='app', postgresql_where=sa.text("status = 'confirmed'"))
    op.drop_index(op.f('ix_app_travel_preferences_user_principal_id'), table_name='travel_preferences', schema='app')
    op.drop_index(op.f('ix_app_travel_preferences_tenant_id'), table_name='travel_preferences', schema='app')
    op.drop_index(op.f('ix_app_travel_preferences_source_message_id'), table_name='travel_preferences', schema='app')
    op.drop_table('travel_preferences', schema='app')
    op.drop_index('uq_message_citations_position', table_name='message_citations', schema='app')
    op.drop_index(op.f('ix_app_message_citations_tenant_id'), table_name='message_citations', schema='app')
    op.drop_index(op.f('ix_app_message_citations_message_id'), table_name='message_citations', schema='app')
    op.drop_table('message_citations', schema='app')
    op.drop_index('uq_message_attachments_position', table_name='message_attachments', schema='app')
    op.drop_index(op.f('ix_app_message_attachments_tenant_id'), table_name='message_attachments', schema='app')
    op.drop_table('message_attachments', schema='app')
    op.drop_index('uq_tool_calls_run_sequence', table_name='tool_calls', schema='app')
    op.drop_index('ix_tool_calls_tenant_tool_created', table_name='tool_calls', schema='app')
    op.drop_index('ix_tool_calls_active', table_name='tool_calls', schema='app', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_app_tool_calls_tenant_id'), table_name='tool_calls', schema='app')
    op.drop_index(op.f('ix_app_tool_calls_agent_run_id'), table_name='tool_calls', schema='app')
    op.drop_table('tool_calls', schema='app')
    op.drop_index('ix_refresh_tokens_session_issued', table_name='refresh_tokens', schema='app')
    op.drop_index('ix_refresh_tokens_expiry', table_name='refresh_tokens', schema='app')
    op.drop_index(op.f('ix_app_refresh_tokens_session_id'), table_name='refresh_tokens', schema='app')
    op.drop_table('refresh_tokens', schema='app')
    op.drop_index('ix_messages_conversation_history', table_name='messages', schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_messages_agent_run', table_name='messages', schema='app', postgresql_where=sa.text('agent_run_id IS NOT NULL'))
    op.drop_index(op.f('ix_app_messages_tenant_id'), table_name='messages', schema='app')
    op.drop_index(op.f('ix_app_messages_conversation_id'), table_name='messages', schema='app')
    op.drop_index(op.f('ix_app_messages_agent_run_id'), table_name='messages', schema='app')
    op.drop_table('messages', schema='app')
    op.drop_index('uq_idempotency_keys_request', table_name='idempotency_keys', schema='app')
    op.drop_index('ix_idempotency_keys_expiry', table_name='idempotency_keys', schema='app')
    op.drop_index('ix_idempotency_keys_conversation', table_name='idempotency_keys', schema='app', postgresql_where=sa.text('conversation_id IS NOT NULL'))
    op.drop_index(op.f('ix_app_idempotency_keys_tenant_id'), table_name='idempotency_keys', schema='app')
    op.drop_index(op.f('ix_app_idempotency_keys_principal_id'), table_name='idempotency_keys', schema='app')
    op.drop_index(op.f('ix_app_idempotency_keys_conversation_id'), table_name='idempotency_keys', schema='app')
    op.drop_index(op.f('ix_app_idempotency_keys_agent_run_id'), table_name='idempotency_keys', schema='app')
    op.drop_table('idempotency_keys', schema='app')
    op.drop_index(op.f('ix_app_api_keys_tenant_id'), table_name='api_keys', schema='app')
    op.drop_index(op.f('ix_app_api_keys_service_principal_id'), table_name='api_keys', schema='app')
    op.drop_index(op.f('ix_app_api_keys_created_by_user_principal_id'), table_name='api_keys', schema='app')
    op.drop_index('ix_api_keys_prefix', table_name='api_keys', schema='app')
    op.drop_index('ix_api_keys_expiry', table_name='api_keys', schema='app')
    op.drop_index('ix_api_keys_active_service_expiry', table_name='api_keys', schema='app', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('api_keys', schema='app')
    op.drop_index('ix_memberships_user_status', table_name='tenant_memberships', schema='app')
    op.drop_table('tenant_memberships', schema='app')
    op.drop_index(op.f('ix_app_service_principals_tenant_id'), table_name='service_principals', schema='app')
    op.drop_index(op.f('ix_app_service_principals_created_by_user_principal_id'), table_name='service_principals', schema='app')
    op.drop_table('service_principals', schema='app')
    op.drop_index('ix_revoked_access_tokens_expiry', table_name='revoked_access_tokens', schema='app')
    op.drop_index(op.f('ix_app_revoked_access_tokens_user_principal_id'), table_name='revoked_access_tokens', schema='app')
    op.drop_table('revoked_access_tokens', schema='app')
    op.drop_index('ix_auth_sessions_expiry', table_name='auth_sessions', schema='app')
    op.drop_index('ix_auth_sessions_active_user_expiry', table_name='auth_sessions', schema='app', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_app_auth_sessions_user_principal_id'), table_name='auth_sessions', schema='app')
    op.drop_index(op.f('ix_app_auth_sessions_tenant_id'), table_name='auth_sessions', schema='app')
    op.drop_table('auth_sessions', schema='app')
    op.drop_index('ix_auth_one_time_tokens_user_purpose_created', table_name='auth_one_time_tokens', schema='app')
    op.drop_index('ix_auth_one_time_tokens_expiry', table_name='auth_one_time_tokens', schema='app')
    op.drop_index(op.f('ix_app_auth_one_time_tokens_user_principal_id'), table_name='auth_one_time_tokens', schema='app')
    op.drop_table('auth_one_time_tokens', schema='app')
    op.drop_index('uq_agent_runs_active_conversation', table_name='agent_runs', schema='app', postgresql_where=sa.text("status IN ('queued', 'running', 'interrupted')"))
    op.drop_index(op.f('ix_app_agent_runs_tenant_id'), table_name='agent_runs', schema='app')
    op.drop_index(op.f('ix_app_agent_runs_principal_id'), table_name='agent_runs', schema='app')
    op.drop_index(op.f('ix_app_agent_runs_conversation_id'), table_name='agent_runs', schema='app')
    op.drop_index('ix_agent_runs_terminal_completed', table_name='agent_runs', schema='app', postgresql_where=sa.text("status IN ('completed', 'failed', 'cancelled')"))
    op.drop_index('ix_agent_runs_tenant_status_created', table_name='agent_runs', schema='app')
    op.drop_index('ix_agent_runs_conversation_created', table_name='agent_runs', schema='app')
    op.drop_table('agent_runs', schema='app')
    op.drop_index('uq_users_active_email_normalized', table_name='users', schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_users_active_status', table_name='users', schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_app_users_tenant_id'), table_name='users', schema='app')
    op.drop_table('users', schema='app')
    op.drop_index('ix_data_deletion_requests_target', table_name='data_deletion_requests', schema='app')
    op.drop_index('ix_data_deletion_requests_due', table_name='data_deletion_requests', schema='app')
    op.drop_index('ix_data_deletion_requests_completed', table_name='data_deletion_requests', schema='app')
    op.drop_index(op.f('ix_app_data_deletion_requests_tenant_id'), table_name='data_deletion_requests', schema='app')
    op.drop_index(op.f('ix_app_data_deletion_requests_target_id'), table_name='data_deletion_requests', schema='app')
    op.drop_index(op.f('ix_app_data_deletion_requests_requested_by_principal_id'), table_name='data_deletion_requests', schema='app')
    op.drop_table('data_deletion_requests', schema='app')
    op.drop_index('ix_conversations_status_history', table_name='conversations', schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_conversations_purge_after', table_name='conversations', schema='app', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('ix_conversations_owner_history', table_name='conversations', schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_app_conversations_tenant_id'), table_name='conversations', schema='app')
    op.drop_index(op.f('ix_app_conversations_owner_principal_id'), table_name='conversations', schema='app')
    op.drop_table('conversations', schema='app')
    op.drop_index('uq_attachments_object_location', table_name='attachments', schema='app')
    op.drop_index('ix_attachments_uploader_created', table_name='attachments', schema='app')
    op.drop_index('ix_attachments_upload_expiry', table_name='attachments', schema='app')
    op.drop_index('ix_attachments_scan_work', table_name='attachments', schema='app', postgresql_where=sa.text("scan_status IN ('pending', 'failed')"))
    op.drop_index(op.f('ix_app_attachments_uploader_principal_id'), table_name='attachments', schema='app')
    op.drop_index(op.f('ix_app_attachments_tenant_id'), table_name='attachments', schema='app')
    op.drop_table('attachments', schema='app')
    op.drop_index('ix_principals_tenant_active', table_name='principals', schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_app_principals_tenant_id'), table_name='principals', schema='app')
    op.drop_table('principals', schema='app')
    op.drop_index('ix_tenants_active_status', table_name='tenants', schema='app', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('tenants', schema='app')
    op.drop_index('ix_security_audit_events_type_occurred', table_name='security_audit_events', schema='app')
    op.drop_index('ix_security_audit_events_tenant_occurred', table_name='security_audit_events', schema='app')
    op.drop_index('ix_security_audit_events_principal_occurred', table_name='security_audit_events', schema='app', postgresql_where=sa.text('principal_id IS NOT NULL'))
    op.drop_index('ix_security_audit_events_occurred', table_name='security_audit_events', schema='app')
    op.drop_index(op.f('ix_app_security_audit_events_tenant_id'), table_name='security_audit_events', schema='app')
    op.drop_index(op.f('ix_app_security_audit_events_request_id'), table_name='security_audit_events', schema='app')
    op.drop_index(op.f('ix_app_security_audit_events_principal_id'), table_name='security_audit_events', schema='app')
    op.drop_table('security_audit_events', schema='app')
    op.execute("DROP SCHEMA IF EXISTS app")
    # ### end Alembic commands ###
